function(find_package_manager_brew COMMAND)
    find_program(BREW_COMMAND brew)
    if(BREW_COMMAND)
        message(STATUS "Package Manager: Homebrew not found")
        set(${COMMAND} ${BREW_COMMAND} PARENT_SCOPE)
    endif()
endfunction()

macro(add_test_target TARGET_NAME SOURCE_FILES)
    add_executable(${TARGET_NAME} ${SOURCE_FILES})
    add_dependencies(${TARGET_NAME} ${CXX_TARGET_PRECOMPILED_STD})
    target_compile_options(${TARGET_NAME} PRIVATE -fmodule-file=std=${CXX_STD_PCM})
    target_link_options(${TARGET_NAME} PRIVATE -stdlib=libc++)
    target_link_libraries(${TARGET_NAME} PRIVATE Catch2::Catch2WithMain ${PROJECT_LIBRARY_TARGET})
endmacro()
